/* ─────────────────────────────────────────────────────────
   Sedimentære bjergarter — aflejret, presset og kittet.

   Én post pr. bjergart. Felterne er beskrevet i LÆS-MIG.md.
   ───────────────────────────────────────────────────────── */

export default [
  {
    id:'konglomerat', kode:'SE-01', nr:[],
    navn:'Konglomerat', andreNavne:['breccie (med kantede sten)'],
    type:'Klastisk · grovkornet',
    kort:'Rullesten, der er kittet sammen — stenalderens beton.',
    kendetegn:'Afrundede sten og grus i en grundmasse af sand, kittet sammen af kisel, kalk eller jernoxid. Har stenene skarpe kanter, hedder bjergarten breccie.',
    kornstoerrelse:'> 2 mm', densitet:'2,3–2,7',
    mineraler:[{navn:'bjergartsstykker'},{id:'kvarts'},{id:'calcit',andel:'ofte kit'}],
    dannelse:'Sten og grus aflejres af hurtigtstrømmende vand — i floder, deltaer og ved kyster — og kittes siden sammen. De runde sten viser, at de er slidt under transport.',
    findested:'Bornholm (Balka), Skotland og Norge. Kalkkittet konglomerat i Alperne.',
    anvendelse:'Bygningssten.',
    forveksles:'Tillit (istidsaflejring med usorterede, ridsede sten).',
    kend:{korn:['store'], syre:false, opbygning:['klaster'], haard:['glas'], farve:['spaettet']},
    farver:['#A8927A','#D6C8B4','#6F5F4E','#C2B09A'], tegning:'klaster',
    placering:'', billeder:[]
  },
  {
    id:'sandsten', kode:'SE-02', nr:[],
    navn:'Sandsten', andreNavne:['Nexø-sandsten','kvartssandsten'],
    type:'Klastisk · mellemkornet',
    kort:'Sammenkittede sandkorn — ru som sandpapir.',
    kendetegn:'Føles ru som sandpapir, og man kan se eller mærke de enkelte sandkorn. Ofte lagdelt. Farven kommer fra kittet: rød af hæmatit, gul-brun af jernhydroxid, hvid af kvarts.',
    kornstoerrelse:'0,06–2 mm', densitet:'2,2–2,6',
    mineraler:[{id:'kvarts',andel:'oftest > 60 %'},{id:'kalifeldspat'},{id:'muskovit'},{id:'haematit',andel:'kit'},{id:'calcit',andel:'kit'}],
    dannelse:'Sand aflejret af floder, hav eller vind begraves, presses sammen og kittes af mineraler, der udfældes fra grundvandet mellem kornene.',
    findested:'Nexø-sandsten og Balka-sandsten på Bornholm; rød sandsten fra Skåne og Dalarna som ledeblokke.',
    anvendelse:'Bygningssten, slibesten — og porøse sandstenslag er magasin for olie, gas og grundvand.',
    forveksles:'Kvartsit (hårdere, brækker gennem kornene) og siltsten (finere).',
    kend:{korn:['fine','store'], syre:false, opbygning:['lagdelt','massiv'], haard:['glas'], farve:['lys','roed']},
    farver:['#C98F66','#E1B48E','#A56E4C'], tegning:'sand',
    se:[{tekst:'Simulering: porøsitet og permeabilitet', href:'/geografi/poroesitetPermeabilitet.html'},{tekst:'Øvelse: oliens migration', href:'/Øvelser/Geografi/oliens-migration/oliens-migration.html'}],
    placering:'', billeder:[]
  },
  {
    id:'lerskifer', kode:'SE-03', nr:[],
    navn:'Lersten og lerskifer', andreNavne:['alunskifer','skiferler'],
    type:'Klastisk · finkornet',
    kort:'Hærdet ler — flækker i tynde lag.',
    kendetegn:'Så finkornet, at den føles glat. Grå, sort eller rødlig og flækker ofte i tynde plader langs lagene. Alunskifer er sort, lugter af svovl, når den slås i stykker, og kan indeholde fossiler af trilobitter.',
    kornstoerrelse:'< 0,004 mm (ler)', densitet:'2,4–2,8',
    mineraler:[{navn:'lermineraler'},{id:'kvarts'},{id:'muskovit'},{id:'pyrit'},{navn:'organisk stof'}],
    dannelse:'Ler bundfælder sig langsomt i stille vand — på dybt hav, i søer og laguner — og presses sammen. Sort skifer er aflejret i iltfrit vand, hvor det organiske stof ikke blev nedbrudt.',
    findested:'Alunskifer fra kambrium og ordovicium på Bornholm (Læså) og i Skåne. Ledeblokke fra Sverige.',
    anvendelse:'Tagskifer (den metamorfe udgave), og sort skifer er kildebjergart for olie og gas.',
    forveksles:'Tagskifer (hårdere, metamorf og med glinsende spalteflader) og siltsten (føles let ru).',
    kend:{korn:['fine'], syre:false, opbygning:['lagdelt','fossiler'], haard:['kniv'], farve:['moerk']},
    farver:['#3A3B3D','#55575A','#27282A'], tegning:'lag',
    se:[{tekst:'Øvelse: oliens migration', href:'/Øvelser/Geografi/oliens-migration/oliens-migration.html'}],
    placering:'', billeder:[]
  },
  {
    id:'kalksten', kode:'SE-04', nr:[],
    navn:'Kalksten', andreNavne:['ortocerkalk','koralkalk','bryozokalk'],
    type:'Biogen · karbonat',
    kort:'Hærdet kalkslam og skaller — bruser kraftigt i saltsyre.',
    kendetegn:'Grå, hvid eller rødlig og ofte med fossiler: bryozoer, muslinger, koraller eller blæksprutter (ortoceratitter). Ridses af kniv og bruser kraftigt med fortyndet saltsyre.',
    kornstoerrelse:'varierer — fra tæt til grove skalstykker', densitet:'2,5–2,7',
    mineraler:[{id:'calcit',andel:'> 90 %'},{navn:'dolomit'},{navn:'ler'}],
    dannelse:'Kalkskaller og kalkslam fra organismer i varmt, lavt hav hober sig op og hærdes. Bryozokalken ved Stevns og Faxe er aflejret i danien, lige efter dinosaurernes uddøen.',
    findested:'Stevns Klint og Faxe Kalkbrud (bryozokalk og koralkalk), Ortocerkalk fra Öland og Gotland som ledeblokke.',
    anvendelse:'Cement, brændt kalk og mørtel, kalkning af marker og bygningssten.',
    forveksles:'Marmor (krystallinsk, glimtende korn) og dolomit (bruser kun svagt).',
    kend:{korn:['fine','store'], syre:true, opbygning:['massiv','lagdelt','fossiler'], haard:['kniv'], farve:['lys']},
    farver:['#E6E1D3','#CFC7B2','#F3EFE4'], tegning:'fossiler',
    placering:'', billeder:[]
  },
  {
    id:'kridt', kode:'SE-05', nr:[],
    navn:'Skrivekridt', andreNavne:['kridt'],
    type:'Biogen · karbonat',
    kort:'Kridtet fra Møns Klint — mikroskopiske kalkskaller fra alger.',
    kendetegn:'Kridhvid, let og blød — smitter af på fingrene og kan ridses med en negl. Bruser kraftigt i syre. Ofte med flintknolde og fossiler som søpindsvin og belemnitter.',
    kornstoerrelse:'< 0,01 mm (coccolitter)', densitet:'1,5–2,2 (meget porøs)',
    mineraler:[{id:'calcit',andel:'> 95 %'}],
    dannelse:'Kalkplader (coccolitter) fra encellede alger drysser ned på bunden af et varmt hav og hober sig op. I kridttiden for 100–66 mio. år siden lå Danmark under et sådant hav.',
    findested:'Møns Klint, Stevns Klint og Rørdal ved Aalborg. Ligger under det meste af Danmark og er et vigtigt grundvandsmagasin.',
    anvendelse:'Tavlekridt, cement, kalk til landbrug og kalkfyldstof.',
    forveksles:'Kalksten (hårdere) og gips (bruser ikke).',
    kend:{korn:['fine'], syre:true, opbygning:['massiv','fossiler'], haard:['negl','kniv'], farve:['lys']},
    farver:['#F6F3EA','#ECE6D6','#FFFFFF'], tegning:'finkornet',
    placering:'', billeder:[]
  },
  {
    id:'flint', kode:'SE-06', nr:[],
    navn:'Flint', andreNavne:['flintesten','chert'],
    type:'Biogen · kisel',
    kort:'Danmarks nationalsten — sort, glat og med knivskarpe brudflader.',
    kendetegn:'Sort, grå eller brun og glat, ofte med en hvid kalkskorpe. Brækker med muslet brud og skarpe kanter. Ridser glas og bruser ikke (kun skorpen gør).',
    kornstoerrelse:'mikrokrystallinsk', densitet:'2,6',
    mineraler:[{id:'kvarts',andel:'mikrokrystallinsk'},{navn:'opal'}],
    dannelse:'Kisel fra svampenåle og kiselalger opløses i kridtslammet og udfældes igen i knolde og lag — ofte i gange gravet af dyr på havbunden.',
    findested:'Lag i kridtet ved Stevns og Møns Klint og overalt på danske strande og marker.',
    anvendelse:'Stenalderens redskaber, flintlåse og fyrtøj.',
    forveksles:'Obsidian (glasblank) og kvartsit (kornet).',
    kend:{korn:['ingen'], syre:false, opbygning:['massiv'], haard:['glas'], farve:['moerk']},
    farver:['#2E2F33','#4B4D52','#F2EEE4'], tegning:'flint',
    placering:'', billeder:[]
  },
  {
    id:'moler', kode:'SE-07', nr:[],
    navn:'Moler', andreNavne:['diatomit'],
    type:'Biogen · kisel',
    kort:'Kiselalger og ler fra Limfjorden — så let, at det kan flyde.',
    kendetegn:'Lys gullig-hvid, meget let og porøs, ofte med tynde mørke askelag. Bruser ikke i syre. Rummer fossiler af fisk og insekter.',
    kornstoerrelse:'< 0,05 mm', densitet:'< 1 (tør)',
    mineraler:[{navn:'opal (kiselalger)'},{navn:'ler'}],
    dannelse:'Skaller af kiselalger aflejret i et havområde for ca. 55 mio. år siden. De mørke lag er vulkansk aske fra den nordatlantiske vulkanisme, da Atlanterhavet åbnede sig.',
    findested:'Kun i Limfjordsområdet: Fur, Mors og Silstrup. Fur-formationen.',
    anvendelse:'Isoleringssten, kattegrus og absorptionsmiddel.',
    forveksles:'Kridt (bruser i syre) og tuf.',
    kend:{korn:['fine'], syre:false, opbygning:['lagdelt','fossiler'], haard:['negl','kniv'], farve:['lys']},
    farver:['#E9DDBF','#D4C39C','#5D5347'], tegning:'lag',
    placering:'', billeder:[]
  },
  {
    id:'kul', kode:'SE-08', nr:[],
    navn:'Kul', andreNavne:['stenkul','brunkul'],
    type:'Organisk',
    kort:'Sammenpresset plantemateriale — sort, let og brændbar.',
    kendetegn:'Sort og let. Stenkul er blankt og hårdt og smitter af; brunkul er brunt, mat og kan vise planterester.',
    kornstoerrelse:'—', densitet:'1,1–1,5',
    mineraler:[{navn:'kulstof og organisk stof'}],
    dannelse:'Planter fra sumpskove begraves uden ilt og bliver til tørv, brunkul og til sidst stenkul, efterhånden som tryk og varme driver vand og gas ud.',
    findested:'Stenkul fra Bornholm (Hasle) og Polen. Brunkul i Midtjylland (Søby) og Tyskland.',
    anvendelse:'Brændsel til kraftværker og til koks i stålindustrien — en stor kilde til CO₂.',
    forveksles:'Alunskifer (tung, brænder ikke) og obsidian (glas, hårdt).',
    kend:{korn:['ingen','fine'], syre:false, opbygning:['massiv','lagdelt'], haard:['negl','kniv'], farve:['moerk']},
    farver:['#161616','#2E2E2E','#0A0A0A'], tegning:'glas',
    placering:'', billeder:[]
  },
  {
    id:'kalktuf', kode:'SE-09', nr:[],
    navn:'Kalktuf', andreNavne:['frådsten','travertin'],
    type:'Kemisk · karbonat',
    kort:'Porøs kalk udfældet ved kilder — med aftryk af blade og mos.',
    kendetegn:'Gullig-hvid, porøs og hullet, ofte med aftryk af blade, kviste og mos. Bruser i syre.',
    kornstoerrelse:'tæt, med hulrum', densitet:'1,5–2,4',
    mineraler:[{id:'calcit',andel:'> 90 %'}],
    dannelse:'Kalkrigt grundvand kommer frem i en kilde, afgiver CO₂ og udfælder kalk på planter og sten.',
    findested:'Ved kalkrige kildevæld, hvor undergrunden er kalk eller kridt. Travertin fra Tivoli ved Rom.',
    anvendelse:'Frådsten er brugt i en del østjyske middelalderkirker; travertin i gulve og facader.',
    forveksles:'Pimpsten og tuf (bruser ikke).',
    kend:{korn:['fine'], syre:true, opbygning:['huller','fossiler'], haard:['kniv'], farve:['lys']},
    farver:['#E5D7B6','#CDBB93','#F2E9D2'], tegning:'blaerer',
    placering:'', billeder:[]
  }
];
